using UnityEngine;

public class Bullet : MonoBehaviour
{
    [Header("ï¿½Ú“ï¿½ï¿½ï¿½ï¿½x")]
    public float speed = 10f;

    [Header("ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½bï¿½j")]
    public float lifeTime = 5f;

    private Vector3 velocity;   // ï¿½ï¿½ï¿½ï¿½ï¿½^ï¿½ï¿½ï¿½Ì•ï¿½ï¿½ï¿½ï¿½xï¿½Nï¿½gï¿½ï¿½

    void Start()
    {
        // ï¿½ï¿½ï¿½Ë’nï¿½_ï¿½ï¿½ï¿½çŒ©ï¿½ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½ï¿½ï¿½ğ³‹Kï¿½ï¿½
        Vector3 targetDirection = (new Vector3(0,1,0) - transform.position).normalized;

        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½^ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½xï¿½xï¿½Nï¿½gï¿½ï¿½
        velocity = targetDirection * speed;

        // ï¿½ï¿½ï¿½ï¿½ï¿½Åï¿½ï¿½ï¿½ï¿½ï¿½
        Destroy(gameObject, lifeTime);
    }

    void Update()
    {
        // ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½^ï¿½ï¿½ï¿½ÅˆÚ“ï¿½
        transform.position += velocity * Time.deltaTime;
    }
}
